services:
  prod-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.prod
    env_file:
      - ./server/.env.production
    ports:
      - "${PROD_SERVER_PORT}:${PROD_SERVER_PORT}"
    networks:
      - prod-network
    depends_on:
      - prod-db

  prod-db:
    image: cleisonfmelo/postgres-pg-cron:latest 
    env_file:
      - ./server/.env.production
    ports:
      - "5431:5432"
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    networks:
      - prod-network

  nginx-proxy:
    build:
      context: .
      dockerfile: ./client/Dockerfile.prod  # Build client + Nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - prod-network
    depends_on:
      - prod-server

volumes:
  prod-db-data:

networks:
  prod-network:
    driver: bridge
