FROM node:24-alpine AS base
RUN apk add --no-cache libc6-compat
RUN corepack enable pnpm

WORKDIR /app
COPY ./server .
RUN --mount=type=cache,target=/pnpm/store \
    pnpm install --frozen-lockfile
EXPOSE 8080
CMD ["pnpm", "start"]
