FROM node:24-alpine AS base

FROM base AS workspace
RUN apk add --no-cache libc6-compat
RUN corepack enable pnpm

FROM workspace AS dependencies
WORKDIR /app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 expressjs 
COPY ./server .
RUN --mount=type=cache,target=/pnpm/store \
    pnpm install --frozen-lockfile

USER expressjs

CMD ["node", "./src/index.js"]
